# Generated by Django 4.1.3 on 2022-11-30 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_record_options_alter_record_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('january', models.DecimalField(decimal_places=2, max_digits=12)),
                ('february', models.DecimalField(decimal_places=2, max_digits=12)),
                ('march', models.DecimalField(decimal_places=2, max_digits=12)),
                ('april', models.DecimalField(decimal_places=2, max_digits=12)),
                ('may', models.DecimalField(decimal_places=2, max_digits=12)),
                ('june', models.DecimalField(decimal_places=2, max_digits=12)),
                ('july', models.DecimalField(decimal_places=2, max_digits=12)),
                ('august', models.DecimalField(decimal_places=2, max_digits=12)),
                ('september', models.DecimalField(decimal_places=2, max_digits=12)),
                ('octuber', models.DecimalField(decimal_places=2, max_digits=12)),
                ('november', models.DecimalField(decimal_places=2, max_digits=12)),
                ('december', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_entry', to='main.record')),
            ],
            options={
                'verbose_name': 'Record Entry',
                'verbose_name_plural': 'Records Entries',
                'db_table': 'main_record_entry',
                'ordering': ('name',),
            },
        ),
    ]
