# Generated by Django 4.1.3 on 2022-12-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_record_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordentry",
            name="entry_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Expense"), (2, "Income")], default=0
            ),
            preserve_default=False,
        ),
    ]
